import type { Metadata } from "next";
import { ThemeProvider } from '@/components/providers/ThemeProvider';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ModalProvider } from '@/components/providers/ModalProvider';
import { ModeToggle } from '@/components/SwitchMode';
import { ThemeSwitcher } from '@/components/SwitchTheme';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider>
          <>
            {children}
            <ModalProvider />
            <ModeToggle />
            <ThemeSwitcher />
          </>
        </ThemeProvider>
      </body>
    </html>
  );
}
