import type { Metadata } from "next";
import { ThemeProvider } from '@/components/providers/ThemeProvider';
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ModalProvider } from '@/components/providers/ModalProvider';
import { ModeToggle } from '@/components/SwitchMode';
import { ThemeSwitcher } from '@/components/SwitchTheme';
import { ShellProvider } from '@/components/providers/ShellProvider';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { getThemeFromCookie } = await import('@/lib/services/theme-cookie');
  const theme = await getThemeFromCookie();

  return (
    <html lang="en" className="dark">
      <body className="antialiased">
        <ThemeProvider initialTheme={theme || 'ios'}>
            <>
              <ShellProvider>
                {children}
              </ShellProvider>
              <ModalProvider />
              {/* <ModeToggle /> */}
              {/* <ThemeSwitcher /> */}
            </>
        </ThemeProvider>
      </body>
    </html>
  );
}
